Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/03/2023
Var
// Seção de Declarações das variáveis 
tempC, tf: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva ("Temperatura em °C: ")
Leia (tempC)
tf <- (9 / 5 * tempC) + 32
Escreva ("A temperatura em Fahrenheit é:", tf, "°F")

Fimalgoritmo