Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/03/2023
Var
// Seção de Declarações das variáveis 
polegadas, mm: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva ("Quantidade de chuva em polegadas: ")
Leia (polegadas)
mm <- polegadas * 25.4
Escreva ("A quantidade de chuva equivalente em mm é:", mm, "mm")

Fimalgoritmo