Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/03/2023
Var
// Seção de Declarações das variáveis 
n, quadrado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva ("Digite um número: ")
Leia (n)
quadrado <- n ^ 2
Escreva ("O quadrado de", n, " é", quadrado)

Fimalgoritmo