Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/03/2023
Var
// Seção de Declarações das variáveis 
custoTot, custoFab: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva ("Custo de fábrica: ")
Leia (custoFab)
custoTot <- (custoFab * 0.12) + (custoFab * 0.45) + custoFab
Escreva ("O custo total do veículo é de R$", custoTot)

Fimalgoritmo