Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/03/2023
Var
// Seção de Declarações das variáveis 
x, y: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva ("Valor de X: ")
Leia (x)
y <- 3 * x + 2
Escreva ("y(x) = 3x + 2; sendo x =", x, ", o valor de y é", y)

Fimalgoritmo