Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/03/2023
Var
// Seção de Declarações das variáveis 
a, b: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva ("Valor A: ")
Leia (a)
Escreva ("Valor B: ")
Leia (b)
se (a > b) entao
   escreva ("A:", a, " é maior do que B")
   senao
        escreva ("A:", a, " não é maior do que B")
fimse

Fimalgoritmo