Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/03/2023
Var
// Seção de Declarações das variáveis 
n1, n2: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Valor 1: ")
leia (n1)
escreva ("Valor 2: ")
leia (n2)
se (n1 > n2) entao
   escreva (n2, n1)
   senao
        escreva (n1, n2)
fimse

Fimalgoritmo