Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/03/2023
Var
// Seção de Declarações das variáveis 
larg, comp, area: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreva ("Largura do terreno(m): ")
Leia (larg)
Escreva ("Comprimento do terreno(m): ")
Leia (comp)
area <- larg * comp
Escreva ("A área do terreno é de", area, "m²")

Fimalgoritmo