Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/03/2023
Var
// Seção de Declarações das variáveis
qtd_cavalos, qtd_ferr: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreva ("Quantidade de cavalos comprados: ")
Leia (qtd_cavalos)
qtd_ferr <- qtd_cavalos * 4
Escreva ("São nessesárias", qtd_ferr, " ferraduras para equipar todos os cavalos")

Fimalgoritmo
