Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/03/2023
Var
// Seção de Declarações das variáveis 
peso_prato, valor_pagar: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Peso do prato(KG): ")
Leia(peso_prato)
valor_pagar <- peso_prato * 12
Escreva("O valor a ser pago pela comida é de R$", valor_pagar)

Fimalgoritmo