Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/03/2023
Var
// Seção de Declarações das variáveis 
salarioI, aumento, salarioF: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva ("Salário do funcionário: R$")
Leia (salarioI)
aumento <- salarioI * 1.15
salarioF <- aumento * 0.92
Escreva ("O salário final do funcionário é de R$", salarioF)

Fimalgoritmo