Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/03/2023
Var
// Seção de Declarações das variáveis 
num1: inteiro
quadrado: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva ("Digite um número: ")
Leia (num1)
quadrado <- num1 ^ 2
Escreva ("O quadrado de", num1, " é:", quadrado)

Fimalgoritmo