Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/03/2023
Var
// Seção de Declarações das variáveis 
area, base, h: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva ("Base do triângulo(cm): ")
Leia (base)
Escreva ("Altura do triângulo(cm): ")
Leia (h)
area <- (base * h) / 2
Escreva ("A área desse triângulo é de:", area, " cm²")

Fimalgoritmo