Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/03/2023
Var
// Seção de Declarações das variáveis 
salario, reajuste: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva ("Salário: ")
Leia (salario)
reajuste <- 1.25 * salario
Escreva ("O seu salário reajustado com um aumento de 25% é de:", reajuste, "R$")
Fimalgoritmo