Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/03/2023
Var
// Seção de Declarações das variáveis 
num1, num2, soma: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva ("Digite um número: ")
Leia (num1)
Escreva("Digite outro número: ")
Leia (num2)
soma <- num1 + num2
Escreva ("A soma desses números é:", soma)

Fimalgoritmo