Algoritmo "ex01"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/05/2023
Var
// Seção de Declarações das variáveis 
cont: inteiro
 vet: vetor [0..7] de inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para cont de 0 ate 7 faca
     vet[cont] <- 999
     escreva (vet[cont])
fimpara

Fimalgoritmo