Algoritmo "ex01"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/03/2023
Var
// Seção de Declarações das variáveis 
n1, n2, n3, media: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Nota 1: ")
leia (n1)
escreva ("Nota 2: ")
leia (n2)
escreva ("Nota 3: ")
leia (n3)
media <- (n1 + n2 + n3) / 3
se (media >= 7) entao
   escreva ("Aluno aprovado!")
fimse
Fimalgoritmo