Algoritmo "ex02"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/03/2023
Var
// Seção de Declarações das variáveis 
temp_f, temp_c: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Temperatura(°F): ")
leia (temp_f)
temp_c <- ((temp_f - 32) * 5) / 9
escreva (temp_f, "°F equivalem a", temp_c, "°C")
Fimalgoritmo