Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/03/2023
Var
// Seção de Declarações das variáveis 
n1, n2: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Número 1: ")
leia (n1)
escreva ("Número 2: ")
leia (n2)

se (n1 > n2) entao
   escreva (n1 - n2)
senao
     escreva (n2 - n1)
fimse
Fimalgoritmo