Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/03/2023
Var
// Seção de Declarações das variáveis 
n: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Digite um valor: ")
leia (n)
se ((n % 2 = 0)) entao
   escreva (n, " é par")
senao
     escreva (n, " é ímpar")
fimse

Fimalgoritmo