Algoritmo "repita_01"
// 
//  
// Descrição   : Escreva um programa que mostre na tela a seguinte contagem: 6 7 8 9 10 11 Acabou!
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/04/2023
Var
// Seção de Declarações das variáveis 
cont: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
cont <- 6
enquanto (cont < 12) faca
         escreva(cont)
         cont <- cont + 1
fimenquanto
escreva (" ACABOU!")

Fimalgoritmo