Algoritmo "ENQUANTO_03"
// 
//  
// Descrição   : Crie um aplicativo que mostre na tela a seguinte contagem: 0 3 6 9 12 15 18 Acabou!
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/04/2023
Var
// Seção de Declarações das variáveis 
cont: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
enquanto (cont < 19) faca
         escreva (cont)
         cont <- cont + 3
fimenquanto
escreva (" ACABOU!")

Fimalgoritmo