Algoritmo "enquanto_02"
// 
//  
// Descrição   : Faça um algoritmo que mostre na tela a seguinte contagem: 10 9 8 7 6 5 4 3 Acabou!
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/04/2023
Var
// Seção de Declarações das variáveis 
cont: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
cont <- 10
enquanto (cont > 2) faca
         escreva (cont)
         cont <- cont - 1
fimenquanto
escreva (" ACABOU!")

Fimalgoritmo