Algoritmo "ENQUANTO_04"
// 
//  
// Descrição   : Desenvolva um programa que mostre na tela a seguinte contagem: 100 95 90 85 80 ... 0
// Acabou!
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/04/2023
Var
// Seção de Declarações das variáveis 
cont: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
cont <- 100
enquanto (cont > -1) faca
         escreva (cont)
         cont <- cont - 5
fimenquanto
escreva (" ACABOU!")

Fimalgoritmo