Algoritmo "PARA_17"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/04/2023
Var
// Seção de Declarações das variáveis 
stop, cont: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Digite o fim da contagem: ")
leia (stop)

para cont de 0 ate stop faca
     escreva (cont)
fimpara
escreva (" FIM!")

Fimalgoritmo