Algoritmo "REPITA_11"
// 
//  
// Descrição   : Crie um programa que mostre na tela a seguinte contagem, usando a estrutura “faça
// enquanto” 0 3 6 9 12 15 18 21 24 27 30 Acabou!
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/04/2023
Var
// Seção de Declarações das variáveis 
cont: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
cont <- 0
repita
      escreva (cont)
      cont <- cont + 3
ate (cont = 33)

Fimalgoritmo