Algoritmo "EX04"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/04/2023
Var
// Seção de Declarações das variáveis 
num: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Digite um valor inteiro: ")
leia (num)
se (num mod 2 = 0) entao
   escreva (num, " é par")
senao
     escreva (num, " é ímpar")
fimse

Fimalgoritmo